# Generated by Django 5.1.1 on 2025-09-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
