# Generated by Django 5.1.1 on 2025-09-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
    ]
